version: "3.3"

services: 
  web: 
    network_mode: host
    image: public.ecr.aws/i3k0c8g9/ytrd-web-dev:latest
    ports: 
      - "3000:3000"
    environment:
      - REACT_APP_GQL_HOST

  gql: 
    network_mode: host
    image: public.ecr.aws/i3k0c8g9/ytrd-gql-dev:latest
    ports: 
      - "4000:4000"
    volumes: 
      - ${PWD}/config.json:/app/config.json
    environment: 
      - GCP_API_KEY

